name: alexandria-db

services:
  REPL-01:
    container_name: repl-01
    hostname: mongo1
    image: 'mongo:7'
    ports:
      - 3010:3010
    restart: no
    command: mongod --port 3010 --bind_ip_all --replSet rset
    env_file:
      - ./../.env
    networks:
      - custom-network
    volumes:
      - ./scripts/mongo/:/scripts/mongo/

  REPL-02:
    container_name: repl-02
    hostname: mongo2
    image: 'mongo:7'
    ports:
      - 3011:3011
    restart: no
    command: mongod --port 3011 --bind_ip_all --replSet rset
    env_file:
      - ./../.env
    networks:
      - custom-network

  REPL-03:
    container_name: repl-03
    hostname: mongo3
    image: 'mongo:7'
    ports:
      - 3012:3012
    restart: no
    command: mongod --port 3012 --bind_ip_all --replSet rset
    env_file:
      - ./../.env
    networks:
      - custom-network

  redis:
    container_name: 'redis-server'
    image: redis:7
    ports:
      - '6379:6379'
    restart: on-failure
    expose:
      - 6379
    volumes:
      - ./redis:/data

networks:
  custom-network:
    driver: bridge
    name: alexandria-network
